force-app/main/default/objects/Connect__c/Connect__c.object-meta.xml
<CustomObject>
    <label>Connect</label>
    <nameField>
        <label>Connect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connect__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Connect__c/fields/Initializer__c.field-meta.xml
<CustomField>
    <fullName>Initializer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initializer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Connects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Connect__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Connect__c/fields/Responder__c.field-meta.xml
<CustomField>
    <fullName>Responder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responder</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ConnectsResponder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RTCContorller.cls
public without sharing class RTCContorller {
	@AuraEnabled
	public static List<User> getUsers() {
		return [
				SELECT Id, Name, Email
				FROM User
				WHERE IsActive = TRUE
		]; // AND Id != :UserInfo.getUserId()
	}

	@AuraEnabled
	public static Id createConnection(String offer, String userId) {
		Connect__c conn = new Connect__c(
				Name = 'Conversation from ' + UserInfo.getUserName(),
				Offer__c = offer,
				Responder__c = userId,
				Initializer__c = UserInfo.getUserId()
		);

		insert conn;
		return conn.Id;
	}

	@AuraEnabled
	public static List<Connect__c> getUserConnections() {
		return [
				SELECT Id, Name, Answer__c, Offer__c, Initializer__c, Responder__c
				FROM Connect__c
				WHERE Responder__c =: UserInfo.getUserId()
				ORDER BY CreatedDate DESC
				LIMIT 20
		];
	}

	@AuraEnabled
	public static void deleteConnection(Id connectionId) {
		Database.delete(connectionId);
	}

	@AuraEnabled
	public static Connect__c getConnection(String connectionId) {
		return [
				SELECT Id, Name, Answer__c, Offer__c, Initializer__c, Responder__c
				FROM Connect__c
				WHERE Id = :connectionId
		];
	}

	@AuraEnabled
	public static void setAnswer(String connectionId, String answer) {
		update new Connect__c(Id = connectionId, Answer__c = answer);
	}
}